version: '3'

services:
  betting-patterns:
    build: .
    volumes:
      - .:/app
      # Don't mount node_modules to avoid overriding container dependencies with host's
      - /app/node_modules
    command: sh -c "npm install && node --no-warnings test-betting-patterns.js"
    environment:
      - NODE_ENV=production

  house-edge:
    build: .
    volumes:
      - .:/app
      # Don't mount node_modules to avoid overriding container dependencies with host's
      - /app/node_modules
    command: sh -c "npm install && node --no-warnings test-house-edge-compounding.js"
    environment:
      - NODE_ENV=production
  
  # Interactive shell for development
  dev:
    build: .
    volumes:
      - .:/app
      # Don't mount node_modules to avoid overriding container dependencies with host's
      - /app/node_modules
    command: sh
    stdin_open: true
    tty: true 