version: '3'

services:
  betting-patterns:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    command: test-betting-patterns.js

  house-edge:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    command: test-house-edge-compounding.js
  
  # Interactive shell for development
  dev:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    entrypoint: /bin/sh
    command: ""
    stdin_open: true
    tty: true 